# Generated by Django 3.2.13 on 2022-06-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField(default=1)),
                ('humidity', models.IntegerField(default=2)),
                ('illumination', models.IntegerField(default=3)),
            ],
        ),
    ]
