# Generated by Django 3.2.13 on 2022-06-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datainfo',
            name='humidity',
            field=models.CharField(default=2, max_length=32),
        ),
        migrations.AlterField(
            model_name='datainfo',
            name='illumination',
            field=models.CharField(default=3, max_length=32),
        ),
        migrations.AlterField(
            model_name='datainfo',
            name='temperature',
            field=models.CharField(default=1, max_length=32),
        ),
    ]
