# Generated by Django 3.2.13 on 2022-06-03 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataInfo', '0002_auto_20220602_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainfo',
            name='picture',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='datainfo',
            name='humidity',
            field=models.CharField(default=2, max_length=64),
        ),
        migrations.AlterField(
            model_name='datainfo',
            name='illumination',
            field=models.CharField(default=3, max_length=64),
        ),
        migrations.AlterField(
            model_name='datainfo',
            name='temperature',
            field=models.CharField(default=1, max_length=64),
        ),
    ]
