# Generated by Django 3.2.13 on 2022-06-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataInfo', '0004_alter_datainfo_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64)),
                ('time', models.CharField(max_length=64)),
            ],
        ),
    ]
