# Generated by Django 3.2.13 on 2022-06-07 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataInfo', '0005_admininfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datainfo',
            name='picture',
        ),
    ]
