# Generated by Django 3.2.13 on 2022-06-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataInfo', '0006_remove_datainfo_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
