# Generated by Django 3.2.13 on 2022-06-10 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataInfo', '0007_alter_admininfo_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adminInfo',
            new_name='rfidInfo',
        ),
    ]
