# Generated by Django 3.2.13 on 2022-06-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataInfo', '0008_rename_admininfo_rfidinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminInfo',
            fields=[
                ('adminid', models.AutoField(primary_key=True, serialize=False)),
                ('adminpwd', models.CharField(default=123, max_length=64)),
                ('adminuid', models.CharField(blank=True, max_length=64, null=True)),
                ('adminname', models.CharField(blank=True, max_length=64, null=True)),
                ('adminphoto', models.ImageField(upload_to='img')),
            ],
        ),
    ]
