# Generated by Django 3.2.13 on 2022-06-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataInfo', '0009_admininfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininfo',
            name='adminphoto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
