# Generated by Django 3.2.13 on 2022-06-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataInfo', '0010_alter_admininfo_adminphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininfo',
            name='adminid',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
