# Generated by Django 3.2.13 on 2022-06-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataInfo', '0011_alter_admininfo_adminid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininfo',
            name='adminphoto',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
