# Generated by Django 3.2.13 on 2022-06-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataInfo', '0013_remove_admininfo_adminphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidinfo',
            name='times',
            field=models.CharField(default=1, max_length=64),
        ),
    ]
